### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by alebarbaja** [vgpena/vgpena.github.io#1]
In the article "[Winning with CSS Variables](https://vgpena.github.io/winning-with-css-variables/)" the link of "Store your color combinations in Sass maps" is broken. It should take us to http://now.violet.is/color-scheming but there's nothing.

**Comment by vgpena** [comment]
Thank you @alebarbaja, this will be fixed in my release later today.

**Comment by vgpena** [comment]
Fixed and deployed: https://vgpena.github.io/winning-with-css-variables/ 🥳
