### ISSUE TITLE
Add visible link to RSS feed

### ISSUE THREAD

**Issue by laras126** [vgpena/vgpena.github.io#3]
Hi there! I would like to subscribe to your blog via RSS but wasn’t able to find a link to the feed - maybe add one when you have a chance?

Cheers - I really like your writing :)

**Comment by vgpena** [comment]
Thank you @laras126, I will add this shortly!

**Comment by vgpena** [comment]
Link is added to the site footer https://vgpena.github.io/ 🥳I appreciate you!
