### ISSUE TITLE
Typo in Using CSS Grid the Right Way

### ISSUE THREAD

**Issue by knurdtech** [vgpena/vgpena.github.io#5]
When you add the article and info sections, the .info should be grid-column: 11 / span 2;

Awesome article. I love it!

**Comment by vgpena** [comment]
Right you are, thank you @knurdtech! This will be fixed in my build later today.

**Comment by vgpena** [comment]
Typo fixed & deployed: https://vgpena.github.io/using-css-grid-the-right-way/ 🎉
